version: '2'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    container_name: postgres
    image: "postgres:alpine"
  express_api:
    container_name: express-api
    build: .
    ports:
      - "1337:8080"
    volumes:
      - .:/usr/src/app
    links:
      -  postgres
    depends_on:
      - "postgres"
